### ISSUE TITLE
When specifying a binning that results in bin edges that are floats, 2DAlphabet will fail

### ISSUE THREAD

**Issue by ammitra** [ammitra/2DAlphabet#7]
The offending lines are in [`binning.py`](https://github.com/ammitra/2DAlphabet/blob/master/TwoDAlphabet/binning.py#L463-L483). 

When the binning results in integer bin edges there is no issue. However, if we wish to split the axis range into something that results in non-integer bins, 2DAlphabet will complain. For instance, here we try to split the X axis, which goes from `[0, 1]` into 20 parts:
```
>>> twoD = TwoDAlphabet('HSPC_fits', 'test.json', loadPrevious=False)
Doing GLOBAL variable replacement in input json...
rebin_axis: <ROOT.TAxis object ("xaxis") at 0x8490148>
old bins (min, max) = (0.0,0.05)                                     <------ OK
new bins (min, max) = (0.0,0.0500000007451)           <------ OK
old bins (min, max) = (0.05,0.1)                                     <------ OK
new bins (min, max) = (0.0,0.0500000007451)           <------ here's the error: the new bins should be (0.05, 0.1), not the same as previously
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uscms_data/d3/ammitra/TamasCombineTest/CMSSW_10_6_14/src/2DAlphabet/TwoDAlphabet/twoDalphabet.py", line 57, in __init__
    self.GetHistMap(), readOnly=False
  File "/uscms_data/d3/ammitra/TamasCombineTest/CMSSW_10_6_14/src/2DAlphabet/TwoDAlphabet/config.py", line 373, in __init__
    self.Add(binnings)
  File "/uscms_data/d3/ammitra/TamasCombineTest/CMSSW_10_6_14/src/2DAlphabet/TwoDAlphabet/config.py", line 396, in Add
    h = copy_hist_with_new_bins(row.out_histname,'X',h,binning.xbinList)
  File "/uscms_data/d3/ammitra/TamasCombineTest/CMSSW_10_6_14/src/2DAlphabet/TwoDAlphabet/binning.py", line 484, in copy_hist_with_new_bins
    Cannot split input bin [%s,%s] with output bin [%s,%s]'''%(axis_to_rebin,old_bin_min,old_bin_max,new_bin_min,new_bin_max))
ValueError: The requested X rebinning does not align bin edges with the input bin edge.
                            Cannot split input bin [0.05,0.1] with output bin [0.0,0.0500000007451]
```

The culprit behind this issue lies in the fact that the [new bin min/max values](https://github.com/ammitra/2DAlphabet/blob/master/TwoDAlphabet/binning.py#L459-L460) may become floats with different precision than the [old bin min/max values](https://github.com/ammitra/2DAlphabet/blob/master/TwoDAlphabet/binning.py#L464-L465) specified in the config file. This can be seen in the above error message

**Comment by ammitra** [comment]
Seemingly fixed in commit 4ae8dcbfd98a340b6c49dfb2e7641167886636af. The added `break` statements are probably overkill, since the loop should break on successful completion of the `if` statement, but I guess it can't hurt. The `round()` function should have no effect on bin edges which are integers. 

A version of this fix with debugging enabled shows the proper behavior:
```
rebin_nbins: 20
rebin_axis: <ROOT.TAxis object ("xaxis") at 0x73b94f8>
nbins rebin_axis: 20
static_bin: 1
rebin: 1
old bin: 1/20
old bins (min, max) = (0.0,0.05)
new bins (min, max) = (0.0,0.05)
We have found the appropriate bin, now we convert
rebin: 2
old bin: 1/20
old bins (min, max) = (0.0,0.05)
new bins (min, max) = (0.05,0.1)
old bin: 2/20
old bins (min, max) = (0.05,0.1)
new bins (min, max) = (0.05,0.1)
We have found the appropriate bin, now we convert
rebin: 3
old bin: 1/20
old bins (min, max) = (0.0,0.05)
new bins (min, max) = (0.1,0.15)
old bin: 2/20
old bins (min, max) = (0.05,0.1)
new bins (min, max) = (0.1,0.15)
old bin: 3/20
old bins (min, max) = (0.1,0.15)
new bins (min, max) = (0.1,0.15)
We have found the appropriate bin, now we convert
```

Here, `rebin` stands for the new bin we are creating and `old bin` the bin number from the original (input) histogram we are evaluating.

We are rebinning from 20 bins (`[0.0, 0.05, 0.1, ..., 0.9, 0.95, 1.0]`) to the same, but now with rounding. We see that the algorithm loops through the old bin min/max values until they match the new ones, at which point they enter the values into the new bin. In cases like this where the new and original binning are identical, then there should be no difference at all between the old and new histo (I would imagine...)
